config/routes.rb
Rails.application.routes.draw do

  get '/home', to: 'base_controller#home'

  get '/help', to: 'base_controller#help'

  get '/about', to: 'base_controller#about'

  root 'base_controller#home'

  get '/signup', to: 'users#new'

  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'

  post   '/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'

  get '/users/:id/changepassword(.:format)', to: 'users#changepassword', as: "user_changepassword"

  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  after_initialize :init

  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:name, presence: true, length: {maximum: 50})
  validates(:email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false})
  validates(:password, presence: true, length: { minimum: 6 }, allow_nil: true)
  validates(:description, length: {maximum: 2500})
  has_secure_password

  # Role Definitions:
  # 1 User
  # 2 Manager
  # 3 Admin
  # 4 Developer(Can only be added on seed)

  # Set Default Value on initialization
  def init
    self.role ||= 1
  end

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

# Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/base_controller_controller.rb
class BaseControllerController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      flash[:success] = "Welcome!"
      redirect_back_or @user
    else
      flash.now[:danger] = "The email or password didn't match our records."
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :changepassword]
  before_action :correct_user, only: [:edit, :update, :changepassword]
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Thanks for creating a new account."
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def changepassword
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation,
                                    :description)
    end

    # Before filters
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #Return Title for page
  def page_title(page_title = "")
    base_title = "Track Your Time"
    if page_title.empty?
      base_title
    else
      base_title + " | " + page_title
    end
  end
end

app/helpers/base_controller_helper.rb
module BaseControllerHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    reset_session
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/base_controller/about.html.erb
<%provide(:title, "About")%>
<h1>About</h1>
<div>This will be the about section of the application.</div>

<script type="text/javascript">
  $(function() {
    $("#nav-about").parent("li").addClass("active");
  });
</script>

app/views/base_controller/help.html.erb
<%provide(:title, "Help")%>
<h1>Help</h1>
<div>This will be the help section of the application.</div>

<script type="text/javascript">
  $(function() {
    $("#nav-help").parent("li").addClass("active");
  });
</script>

app/views/base_controller/home.html.erb
<%provide(:title, "Home")%>
<h1>Home</h1>
<div>This will be the home section of the application.</div>


<script type="text/javascript">
  $(function() {
    $("#nav-home").parent("li").addClass("active");
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <header class="container-fluid">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="<%= url_for(action: 'home', controller: 'base_controller') %>">Track Your Time</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;">
              <ul class="nav navbar-nav">
                <li><a id="nav-about" href="<%= url_for(action: 'about', controller: 'base_controller') %>">About</a></li>
                <li><a id="nav-help" href="<%= url_for(action: 'help', controller: 'base_controller') %>">Help</a></li>
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Tracking
                  <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Start A Session</a></li>
                    <li><a href="#">Contiue A Previous Session</a></li>
                    <li><a href="#">Manage All Sessions</a></li>
                  </ul>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Edit User Details", edit_user_path(current_user) %></li>
                    <li><%= link_to "Change Password", user_changepassword_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Log out", logout_path, method: :delete %>
                    </li>
                  </ul>
                </li>
                <% else %>
                <li><a href="<%= url_for(action: 'new', controller: 'users') %>"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li><a href="<%= url_for(action: 'new', controller: 'sessions') %>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <div class="container-fluid body-container">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
        <%= yield %>
      </div>
      <div class="container-fluid">
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user_details_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
  <% if not logged_in?%>
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  <% end %>
  <%= f.label :description, "Description" %>
  <%= f.text_area :description, rows:"10", class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/changepassword.html.erb
<% provide(:title, "Update Your Password") %>
<% provide(:button_text, 'Save changes') %>

<h1>Update Your Password</h1>

<div class="row">
  <div class="col-md-6">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit User Details") %>
<% provide(:button_text, 'Save changes') %>
<h1>Update Your User Profile</h1>

<div class="row">
  <div class="col-md-6">
    <%= render "user_details_form" %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Create A New User') %>
<% provide(:button_text, 'Create A New User') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6">
    <%= render "user_details_form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-12">
    <div class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
      <h4 style="margin-left: 5px;">
        Role:
        <% case @user.role
          when 1 %><span>User</span>
          <% when 2 %><span>Manager</span>
          <% when 3 %><span>Administrator</span>
          <% when 4 %><span>Developer</span>
        <% end %>
      </h4>
      <hr>
      <h4>My User Description:</h4>
      <div class="col-md-6">
        <%= @user.description %>
      </div>
    </div>
  </div>
</div>